 name: cortex ai deployment

 on:
    push:
        branches:
            - main
            - test-working-version

 env:
  AWS_REGION: ${{ secrets.AWS_REGION }} 
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} 

 jobs:

    deploy-backend: 
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: aws configure
            uses: aws-actions/configure-aws-credentials@v4
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
                
          - name: login to ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2
          
          - name: Build Gateway
            run: |
              docker build \
              -f Backend/gateway/Dockerfile \
              -t gateway Backend


          - name: tag Gateway
            run:  |
              docker tag gateway:latest \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/gateway:latest

          - name: push Gateway
            run:  |
              docker push \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/gateway:latest


          - name: Build Auth
            run: |
              docker build \
              -f Backend/services/auth/Dockerfile \
              -t auth-service Backend


          - name: tag auth
            run:  |
              docker tag auth-service:latest \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest

          - name: push auth
            run:  |
              docker push \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/auth-service:latest
              


          - name: Build Chat
            run: |
              docker build \
              -f Backend/services/chat/Dockerfile \
              -t chat-service Backend


          - name: tag chat
            run:  |
              docker tag chat-service:latest \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/chat-service:latest

          - name: push chat
            run:  |
              docker push \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/chat-service:latest
              



          - name: Build Agent
            run: |
              docker build \
              -f Backend/services/agent/Dockerfile \
              -t agent-service Backend


          - name: tag agent
            run:  |
              docker tag agent-service:latest \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/agent-service:latest

          - name: push agent
            run: |
              docker push \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/agent-service:latest
              
              
          - name: Build Billing
            run: |
              docker build \
              -f Backend/services/billing/Dockerfile \
              -t billing-service Backend



          - name: tag billing
            run:  |
              docker tag billing-service:latest \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/billing-service:latest

          - name: push billing
            run:  |
              docker push \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/billing-service:latest
              


          - name: deploy gateway
            run:  |
              aws ecs update-service \
              --cluster ${{secrets.ECS_CLUSTER}} \
              --service ${{secrets.GATEWAY_SERVICE}} \
              --force-new-deployment 


          - name: deploy auth
            run:  |
              aws ecs update-service \
              --cluster ${{secrets.ECS_CLUSTER}} \
              --service ${{secrets.AUTH_SERVICE}} \
              --force-new-deployment 

          - name: deploy chat
            run:  |
              aws ecs update-service \
              --cluster ${{secrets.ECS_CLUSTER}} \
              --service ${{secrets.CHAT_SERVICE}} \
              --force-new-deployment 

          - name: deploy agent
            run:  |
              aws ecs update-service \
              --cluster ${{secrets.ECS_CLUSTER}} \
              --service ${{secrets.AGENT_SERVICE}} \
              --force-new-deployment 

          - name: deploy billing
            run:  |
              aws ecs update-service \
              --cluster ${{secrets.ECS_CLUSTER}} \
              --service ${{secrets.BILLING_SERVICE}} \
              --force-new-deployment 
          

    deploy-frontend:
        needs: deploy-backend
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          
          - name: build fronent
            run:  |
                cd Frontend
                npm install
                npm run build

          - name: aws configure
            uses: aws-actions/configure-aws-credentials@v4
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
                
          - name: upload to S3
            run:  |
                aws s3 sync \
                Frontend/dist \
                s3://${{ secrets.S3_BUCKET }} \
                --delete

          - name: invalidate cloudfront
            run:  |
                aws cloudfront create-invalidation \
                --distribution-id \
                ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
                --path "/*"